In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

import os

In [2]:
daily_weather_df_array = []
for file in os.listdir("../toronto-weather-datasets-daily-2014-2024"):
    if file.endswith(".csv"):
        df = pd.read_csv(f"../toronto-weather-datasets-daily-2014-2024/{file}")
        daily_weather_df_array.append(df)
daily_weather_df = pd.concat(daily_weather_df_array)
daily_weather_df = daily_weather_df.reset_index(drop=True)
daily_weather_df

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),Max Temp Flag,Min Temp (°C),Min Temp Flag,Mean Temp (°C),Mean Temp Flag,Heat Deg Days (°C),Heat Deg Days Flag,Cool Deg Days (°C),Cool Deg Days Flag,Total Rain (mm),Total Rain Flag,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-79.63,43.68,TORONTO INTL A,6158731,2024-01-01,2024,1,1,NaN,-1.4,NaN,-3.7,NaN,-2.6,NaN,20.6,NaN,0.0,NaN,0.0,NaN,0.4,NaN,0.2,NaN,2.0,NaN,32.0,NaN,31.0,NaN
1,-79.63,43.68,TORONTO INTL A,6158731,2024-01-02,2024,1,2,NaN,0.6,NaN,-2.5,NaN,-1.0,NaN,19.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,25.0,NaN,40.0,NaN
2,-79.63,43.68,TORONTO INTL A,6158731,2024-01-03,2024,1,3,NaN,2.4,NaN,-0.4,NaN,1.0,NaN,17.0,NaN,0.0,NaN,0.0,NaN,0.0,T,0.0,T,0.0,T,26.0,NaN,37.0,NaN
3,-79.63,43.68,TORONTO INTL A,6158731,2024-01-04,2024,1,4,NaN,0.8,NaN,-6.2,NaN,-2.7,NaN,20.7,NaN,0.0,NaN,0.0,NaN,0.0,T,0.0,T,NaN,NaN,33.0,NaN,53.0,NaN
4,-79.63,43.68,TORONTO INTL A,6158731,2024-01-05,2024,1,5,NaN,-0.7,NaN,-2.9,NaN,-1.8,NaN,19.8,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,24.0,NaN,35.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4013,-79.63,43.68,TORONTO INTL A,6158731,2015-12-27,2015,12,27,NaN,3.5,NaN,-1.7,NaN,0.9,NaN,17.1,NaN,0.0,NaN,3.6,NaN,0.0,NaN,3.6,NaN,NaN,NaN,34.0,NaN,54,NaN
4014,-79.63,43.68,TORONTO INTL A,6158731,2015-12-28,2015,12,28,NaN,0.2,NaN,-6.7,NaN,-3.3,NaN,21.3,NaN,0.0,NaN,11.8,NaN,3.2,NaN,14.8,NaN,0.0,NaN,10.0,NaN,65,NaN
4015,-79.63,43.68,TORONTO INTL A,6158731,2015-12-29,2015,12,29,NaN,4.0,NaN,0.3,NaN,2.2,NaN,15.8,NaN,0.0,NaN,13.6,NaN,0.0,T,13.6,NaN,2.0,NaN,10.0,NaN,72,NaN
4016,-79.63,43.68,TORONTO INTL A,6158731,2015-12-30,2015,12,30,NaN,3.9,NaN,0.7,NaN,2.3,NaN,15.7,NaN,0.0,NaN,0.0,NaN,0.0,T,0.0,T,1.0,NaN,24.0,NaN,32,NaN
4017,-79.63,43.68,TORONTO INTL A,6158731,2015-12-31,2015,12,31,NaN,1.1,NaN,-0.3,NaN,0.4,NaN,17.6,NaN,0.0,NaN,0.2,NaN,0.0,T,0.2,NaN,0.0,NaN,29.0,NaN,50,NaN

In [3]:
daily_weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4018 entries, 0 to 4017
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Longitude (x)              4018 non-null   float64
 1   Latitude (y)               4018 non-null   float64
 2   Station Name               4018 non-null   object
 3   Climate ID                 4018 non-null   int64
 4   Date/Time                  4018 non-null   object
 5   Year                       4018 non-null   int64
 6   Month                      4018 non-null   int64
 7   Day                        4018 non-null   int64
 8   Data Quality               0 non-null      float64
 9   Max Temp (°C)              3998 non-null   float64
 10  Max Temp Flag              24 non-null     object
 11  Min Temp (°C)              3997 non-null   float64
 12  Min Temp Flag              25 non-null     object
 13  Mean Temp (°C)             3995 non-null   float64
 14  Mean Temp Flag             26 non-null     object
 15  Heat Deg Days (°C)         3995 non-null   float64
 16  Heat Deg Days Flag         26 non-null     object
 17  Cool Deg Days (°C)         3995 non-null   float64
 18  Cool Deg Days Flag         26 non-null     object
 19  Total Rain (mm)            3989 non-null   float64
 20  Total Rain Flag            331 non-null    object
 21  Total Snow (cm)            3998 non-null   float64
 22  Total Snow Flag            373 non-null    object
 23  Total Precip (mm)          4000 non-null   float64
 24  Total Precip Flag          611 non-null    object
 25  Snow on Grnd (cm)          990 non-null    float64
 26  Snow on Grnd Flag          281 non-null    object
 27  Dir of Max Gust (10s deg)  3193 non-null   float64
 28  Dir of Max Gust Flag       423 non-null    object
 29  Spd of Max Gust (km/h)     3562 non-null   object
 30  Spd of Max Gust Flag       455 non-null    object
dtypes: float64(13), int64(4), object(14)
memory usage: 973.2+ KB

Remove data after Jan 1 2025

In [4]:
daily_weather_df = daily_weather_df[(daily_weather_df["Year"] != 2025) | ((daily_weather_df["Year"] == 2025) & (daily_weather_df["Month"] == 1) & (daily_weather_df["Day"] == 1))].copy()

In [5]:
daily_weather_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4018 entries, 0 to 4017
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Longitude (x)              4018 non-null   float64
 1   Latitude (y)               4018 non-null   float64
 2   Station Name               4018 non-null   object
 3   Climate ID                 4018 non-null   int64
 4   Date/Time                  4018 non-null   object
 5   Year                       4018 non-null   int64
 6   Month                      4018 non-null   int64
 7   Day                        4018 non-null   int64
 8   Data Quality               0 non-null      float64
 9   Max Temp (°C)              3998 non-null   float64
 10  Max Temp Flag              24 non-null     object
 11  Min Temp (°C)              3997 non-null   float64
 12  Min Temp Flag              25 non-null     object
 13  Mean Temp (°C)             3995 non-null   float64
 14  Mean Temp Flag             26 non-null     object
 15  Heat Deg Days (°C)         3995 non-null   float64
 16  Heat Deg Days Flag         26 non-null     object
 17  Cool Deg Days (°C)         3995 non-null   float64
 18  Cool Deg Days Flag         26 non-null     object
 19  Total Rain (mm)            3989 non-null   float64
 20  Total Rain Flag            331 non-null    object
 21  Total Snow (cm)            3998 non-null   float64
 22  Total Snow Flag            373 non-null    object
 23  Total Precip (mm)          4000 non-null   float64
 24  Total Precip Flag          611 non-null    object
 25  Snow on Grnd (cm)          990 non-null    float64
 26  Snow on Grnd Flag          281 non-null    object
 27  Dir of Max Gust (10s deg)  3193 non-null   float64
 28  Dir of Max Gust Flag       423 non-null    object
 29  Spd of Max Gust (km/h)     3562 non-null   object
 30  Spd of Max Gust Flag       455 non-null    object
dtypes: float64(13), int64(4), object(14)
memory usage: 1004.5+ KB

In [6]:
def list_all_column_values(df):
    for column_name, column in df.items():
        print(daily_weather_df.value_counts(column_name))
        print(" ")

list_all_column_values(daily_weather_df)

Longitude (x)
-79.63    4018
dtype: int64

Latitude (y)
43.68    4018
dtype: int64

Station Name
TORONTO INTL A    4018
dtype: int64

Climate ID
6158731    4018
dtype: int64

Date/Time
2014-01-01    1
2021-05-07    1
2021-04-24    1
2021-04-25    1
2021-04-26    1
             ..
2017-09-06    1
2017-09-07    1
2017-09-08    1
2017-09-09    1
2024-12-31    1
Length: 4018, dtype: int64

Year
2016    366
2020    366
2024    366
2014    365
2015    365
2017    365
2018    365
2019    365
2021    365
2022    365
2023    365
dtype: int64

Month
1     341
3     341
5     341
7     341
8     341
10    341
12    341
4     330
6     330
9     330
11    330
2     311
dtype: int64

Day
1     132
2     132
28    132
27    132
26    132
25    132
24    132
23    132
22    132
21    132
20    132
19    132
18    132
17    132
16    132
15    132
14    132
13    132
12    132
11    132
10    132
9     132
8     132
7     132
6     132
5     132
4     132
3     132
29    124
30    121
31     77
dtype: int64

Series([], dtype: int64)

Max Temp (°C)
 4.2     26
 25.6    22
 24.6    21
 16.8    21
 23.7    21
         ..
-9.5      1
-10.4     1
-10.5     1
-10.7     1
 36.0     1
Length: 486, dtype: int64

Max Temp Flag
M    20
E     4
dtype: int64

Min Temp (°C)
 0.8     28
 14.4    25
-0.6     24
-2.8     23
 15.6    23
         ..
-18.3     1
-18.8     1
-18.9     1
-19.0     1
 25.0     1
Length: 449, dtype: int64

Min Temp Flag
M    21
E     4
dtype: int64

Mean Temp (°C)
 20.3    27
 6.2     24
 1.1     24
 22.3    24
 1.6     21
         ..
-12.5     1
-12.4     1
-11.8     1
-9.1      1
 30.5     1
Length: 456, dtype: int64

Mean Temp Flag
M    23
E     3
dtype: int64

Heat Deg Days (°C)
0.0     1129
11.8      24
16.9      24
16.4      21
14.9      20
        ...
32.1       1
31.9       1
29.8       1
31.1       1
40.3       1
Length: 347, dtype: int64

Heat Deg Days Flag
M    23
E     3
dtype: int64

Cool Deg Days (°C)
0.0     2879
2.3       27
4.3       24
3.5       21
0.8       21
        ...
10.6       1
10.8       1
11.0       1
11.1       1
12.5       1
Length: 110, dtype: int64

Cool Deg Days Flag
M    23
E     3
dtype: int64

Total Rain (mm)
0.0      2689
0.2       121
0.4        82
0.6        77
0.8        50
         ...
4.7         1
21.8        1
21.7        1
5.1         1
128.3       1
Length: 189, dtype: int64

Total Rain Flag
T    302
M     29
dtype: int64

Total Snow (cm)
0.0     3526
0.2       76
0.4       71
0.6       31
0.8       25
        ...
8.0        1
7.8        1
3.1        1
2.5        1
29.2       1
Length: 70, dtype: int64

Total Snow Flag
T    354
M     19
dtype: int64

Total Precip (mm)
0.0      2356
0.2       163
0.4       135
0.6       104
1.0        69
         ...
23.8        1
3.9         1
24.2        1
24.6        1
128.3       1
Length: 192, dtype: int64

Total Precip Flag
T    592
M     18
E      1
dtype: int64

Snow on Grnd (cm)
0.0     324
1.0     126
2.0     101
3.0      53
4.0      43
5.0      42
7.0      31
8.0      29
6.0      26
14.0     25
12.0     24
13.0     18
11.0     18
9.0      17
10.0     15
18.0     15
15.0     14
16.0     13
17.0     12
20.0     11
19.0     11
21.0      5
22.0      5
23.0      3
30.0      3
25.0      2
28.0      2
32.0      1
38.0      1
dtype: int64

Snow on Grnd Flag
T    243
E     38
dtype: int64

Dir of Max Gust (10s deg)
26.0    190
28.0    179
30.0    178
29.0    175
32.0    174
27.0    173
25.0    163
33.0    142
31.0    133
35.0    126
23.0    126
24.0    118
34.0    113
22.0    101
10.0     97
9.0      92
36.0     90
16.0     79
11.0     79
21.0     77
1.0      69
15.0     67
20.0     56
8.0      47
7.0      44
12.0     39
19.0     38
14.0     35
2.0      34
18.0     28
17.0     27
6.0      25
5.0      24
4.0      21
3.0      17
13.0     12
0.0       5
dtype: int64

Dir of Max Gust Flag
M    423
dtype: int64

Spd of Max Gust (km/h)
<31      368
39.0     106
41.0     105
41        95
43        94
        ...
96.0       1
121.0      1
95         1
104        1
119        1
Length: 104, dtype: int64

Spd of Max Gust Flag
M    455
dtype: int64

We would like to add an extra column for displaying the day in unix terms, and then sort the dataset by datetime.

In [7]:
from datetime import datetime
daily_weather_df["Datetime"] = 0
daily_weather_df["Datetime"] = daily_weather_df.apply(lambda row: int(datetime(row.Year, row.Month, row.Day, 0, 0, 0).timestamp() * 1000), axis=1)
daily_weather_df.sort_values(by=['Datetime'], inplace=True)
daily_weather_df

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),Max Temp Flag,Min Temp (°C),Min Temp Flag,Mean Temp (°C),Mean Temp Flag,Heat Deg Days (°C),Heat Deg Days Flag,Cool Deg Days (°C),Cool Deg Days Flag,Total Rain (mm),Total Rain Flag,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag,Datetime
2192,-79.63,43.68,TORONTO INTL A,6158731,2014-01-01,2014,1,1,NaN,-10.0,NaN,-15.3,NaN,-12.7,NaN,30.7,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,3.0,NaN,27.0,NaN,35,NaN,1388552400000
2193,-79.63,43.68,TORONTO INTL A,6158731,2014-01-02,2014,1,2,NaN,-15.2,NaN,-20.0,NaN,-17.6,NaN,35.6,NaN,0.0,NaN,0.0,NaN,1.0,NaN,0.8,NaN,3.0,NaN,35.0,NaN,48,NaN,1388638800000
2194,-79.63,43.68,TORONTO INTL A,6158731,2014-01-03,2014,1,3,NaN,-9.2,NaN,-23.8,NaN,-16.5,NaN,34.5,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,4.0,NaN,21.0,NaN,41,NaN,1388725200000
2195,-79.63,43.68,TORONTO INTL A,6158731,2014-01-04,2014,1,4,NaN,-0.4,NaN,-9.2,NaN,-4.8,NaN,22.8,NaN,0.0,NaN,0.0,NaN,0.4,NaN,0.4,NaN,4.0,NaN,23.0,NaN,57,NaN,1388811600000
2196,-79.63,43.68,TORONTO INTL A,6158731,2014-01-05,2014,1,5,NaN,-0.1,NaN,-2.6,NaN,-1.4,NaN,19.4,NaN,0.0,NaN,1.8,NaN,11.6,NaN,14.4,NaN,6.0,NaN,NaN,NaN,<31,NaN,1388898000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,-79.63,43.68,TORONTO INTL A,6158731,2024-12-27,2024,12,27,NaN,2.2,NaN,0.0,NaN,1.1,NaN,16.9,NaN,0.0,NaN,0.0,T,0.0,NaN,0.0,T,4.0,NaN,7.0,NaN,36.0,NaN,1735275600000
362,-79.63,43.68,TORONTO INTL A,6158731,2024-12-28,2024,12,28,NaN,9.7,NaN,1.3,NaN,5.5,NaN,12.5,NaN,0.0,NaN,0.8,NaN,0.0,NaN,0.8,NaN,0.0,T,NaN,M,NaN,M,1735362000000
363,-79.63,43.68,TORONTO INTL A,6158731,2024-12-29,2024,12,29,NaN,10.3,NaN,2.2,NaN,6.3,NaN,11.7,NaN,0.0,NaN,25.1,NaN,0.0,NaN,25.1,NaN,NaN,NaN,19.0,NaN,48.0,NaN,1735448400000
364,-79.63,43.68,TORONTO INTL A,6158731,2024-12-30,2024,12,30,NaN,9.5,NaN,2.0,NaN,5.8,NaN,12.2,NaN,0.0,NaN,1.2,NaN,0.0,NaN,1.2,NaN,NaN,NaN,18.0,NaN,67.0,NaN,1735534800000
365,-79.63,43.68,TORONTO INTL A,6158731,2024-12-31,2024,12,31,NaN,4.2,NaN,-0.8,NaN,1.7,NaN,16.3,NaN,0.0,NaN,1.6,NaN,0.0,NaN,1.6,NaN,NaN,NaN,36.0,NaN,41.0,NaN,1735621200000